default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: timeboxer_development

test:
  <<: *default
  database: timeboxer_test
    # On Heroku and other platform providers, you may have a full connection URL
    # available as an environment variable. For example:
    #
    #   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
    #
    # You can use this database configuration with:
    #
    #   production:
    #     url: <%= ENV['DATABASE_URL'] %>
    #
production:
  <<: *default
  database: timeboxer_production
  username: timeboxer
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
